from __future__ import annotations

import json
import re
import shutil
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from .db import _eidolon_home
from .scope import ScopeDocument
from .templates import LoadedTemplate

_SLUG_RE = re.compile(r"[^a-z0-9-]+")


class WorkspaceError(Exception):
    """Raised when a workspace operation fails."""

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


def _now_iso() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d")


def _slugify(value: str) -> str:
    lowered = value.strip().lower()
    cleaned = _SLUG_RE.sub("-", lowered).strip("-")
    return cleaned or "untitled"


def engagement_root(engagement_id: str) -> Path:
    return _eidolon_home() / "engagements" / engagement_id


def workspace_root(engagement_id: str) -> Path:
    return engagement_root(engagement_id) / "workspace"


class EngagementWorkspace:
    """On-disk Markdown workspace for a single engagement.

    Layout:
      <home>/engagements/<id>/workspace/
        manifest.json     - template + scope provenance
        scope.md          - declared scope, overwritten on init
        notes/YYYY-MM-DD.md
        decisions/<fork-id>.md
        findings/<slug>.md
        log.jsonl         - append-only event log
    """

    def __init__(self, engagement_id: str) -> None:
        if not engagement_id:
            raise WorkspaceError("engagement_id required")
        self.engagement_id = engagement_id
        self.root = workspace_root(engagement_id)

    @property
    def manifest_path(self) -> Path:
        return self.root / "manifest.json"

    @property
    def scope_path(self) -> Path:
        return self.root / "scope.md"

    @property
    def notes_dir(self) -> Path:
        return self.root / "notes"

    @property
    def decisions_dir(self) -> Path:
        return self.root / "decisions"

    @property
    def findings_dir(self) -> Path:
        return self.root / "findings"

    @property
    def log_path(self) -> Path:
        return self.root / "log.jsonl"

    def exists(self) -> bool:
        return self.root.is_dir()

    def init_from_template(
        self,
        loaded: LoadedTemplate,
        scope: ScopeDocument,
    ) -> None:
        """Create the workspace by copying the template skeleton and writing
        scope + manifest. Idempotent: re-running with the same template+scope
        does not destroy operator edits to notes/decisions/findings."""
        if self.root.exists():
            raise WorkspaceError(f"workspace already initialized: {self.root}")

        self.root.parent.mkdir(parents=True, exist_ok=True)
        if loaded.workspace_skeleton_path is not None:
            shutil.copytree(loaded.workspace_skeleton_path, self.root)
        else:
            self.root.mkdir(parents=True)

        self.notes_dir.mkdir(parents=True, exist_ok=True)
        self.decisions_dir.mkdir(parents=True, exist_ok=True)
        self.findings_dir.mkdir(parents=True, exist_ok=True)

        self._write_scope(scope)
        self._write_manifest(loaded, scope)
        self.append_log("workspace_init", {"template": loaded.template.name})

    def _write_scope(self, scope: ScopeDocument) -> None:
        body = self._render_scope_md(scope)
        self.scope_path.write_text(body)

    def _render_scope_md(self, scope: ScopeDocument) -> str:
        out = [
            "# Scope",
            "",
            "_Auto-generated by the orchestrator. Do not edit by hand._",
            "",
            f"- **Generated:** {_now_iso()}",
            f"- **Default tier:** `{scope.tier}`",
        ]
        if scope.expires_at is not None:
            out.append(f"- **Expires (epoch s):** `{scope.expires_at}`")
        out.append("")
        out.append("## Allowed CIDRs")
        if scope.allowed_cidrs:
            for entry in scope.allowed_cidrs:
                out.append(f"- `{entry}`")
        else:
            out.append("_none declared_")
        out.append("")
        out.append("## Allowed actions")
        if scope.allowed_actions:
            for entry in scope.allowed_actions:
                out.append(f"- `{entry}`")
        else:
            out.append("_none declared_")
        out.append("")
        if scope.rules_of_engagement:
            out.append("## Rules of engagement")
            out.append("")
            out.append(scope.rules_of_engagement.rstrip())
            out.append("")
        return "\n".join(out) + "\n"

    def _write_manifest(self, loaded: LoadedTemplate, scope: ScopeDocument) -> None:
        manifest = {
            "engagement_id": self.engagement_id,
            "template": {
                "name": loaded.template.name,
                "version": loaded.template.version,
                "directory": str(loaded.directory),
            },
            "created_at": _now_iso(),
            "scope_summary": {
                "tier": scope.tier,
                "allowed_cidrs": list(scope.allowed_cidrs),
                "allowed_actions": list(scope.allowed_actions),
            },
        }
        self.manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    def write_note(self, body: str, *, date: str | None = None) -> Path:
        if not body.strip():
            raise WorkspaceError("note body is empty")
        self.notes_dir.mkdir(parents=True, exist_ok=True)
        day = date or _today()
        path = self.notes_dir / f"{day}.md"
        header = "" if path.exists() else f"# Notes - {day}\n\n"
        stamp = _now_iso()
        chunk = f"{header}## {stamp}\n\n{body.rstrip()}\n\n"
        with path.open("a") as fh:
            fh.write(chunk)
        self.append_log("note_appended", {"date": day, "bytes": len(chunk)})
        return path

    def write_decision(
        self,
        fork_id: str,
        *,
        prompt: str,
        resolution: str,
        operator: str,
        rationale: str = "",
    ) -> Path:
        if not fork_id:
            raise WorkspaceError("fork_id required")
        self.decisions_dir.mkdir(parents=True, exist_ok=True)
        path = self.decisions_dir / f"{_slugify(fork_id)}.md"
        body = (
            f"# Decision: {fork_id}\n\n"
            f"- **Resolved:** {_now_iso()}\n"
            f"- **Operator:** {operator}\n"
            f"- **Resolution:** {resolution}\n\n"
            f"## Prompt\n\n{prompt.rstrip()}\n\n"
            f"## Rationale\n\n{rationale.rstrip() or '_(none provided)_'}\n"
        )
        path.write_text(body)
        self.append_log(
            "decision_written",
            {"fork_id": fork_id, "resolution": resolution, "operator": operator},
        )
        return path

    def write_finding(
        self,
        title: str,
        *,
        severity: str,
        body: str,
        cwe: str | None = None,
    ) -> Path:
        if not title.strip():
            raise WorkspaceError("finding title required")
        self.findings_dir.mkdir(parents=True, exist_ok=True)
        slug = _slugify(title)
        path = self.findings_dir / f"{slug}.md"
        cwe_line = f"- **CWE:** {cwe}\n" if cwe else ""
        rendered = (
            f"# {title}\n\n"
            f"- **Severity:** {severity}\n"
            f"- **Recorded:** {_now_iso()}\n"
            f"{cwe_line}"
            f"\n{body.rstrip()}\n"
        )
        path.write_text(rendered)
        self.append_log(
            "finding_written",
            {"title": title, "slug": slug, "severity": severity},
        )
        return path

    def append_log(self, kind: str, payload: dict[str, Any]) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        record = {
            "ts": int(time.time()),
            "iso": _now_iso(),
            "kind": kind,
            "payload": payload,
        }
        with self.log_path.open("a") as fh:
            fh.write(json.dumps(record, sort_keys=True) + "\n")

    def read_log(self) -> list[dict[str, Any]]:
        if not self.log_path.is_file():
            return []
        out: list[dict[str, Any]] = []
        with self.log_path.open("r") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                out.append(json.loads(line))
        return out

    def erase(self) -> None:
        """Best-effort on-disk wipe. Removes the entire workspace directory."""
        if not self.root.exists():
            return
        shutil.rmtree(self.root)
